import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <header className="bg-gray-800 text-white p-4">
          <nav className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-xl font-bold hover:text-gray-300 transition-colors">
              Inicio
            </Link>
            <ul className="flex space-x-6">
              <li>
                <Link href="/contacto" className="hover:text-gray-300 transition-colors">
                  Contacto
                </Link>
              </li>
              <li>
                <Link href="/productos" className="hover:text-gray-300 transition-colors">
                  Productos
                </Link>
              </li>
              <li>
                <Link href="/blog" className="hover:text-gray-300 transition-colors">
                  Blog
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
